### ISSUE TITLE
Name "Type" or "Datatype" ?

### ISSUE THREAD

**Issue by brong** [brong/draft-gondwana-jmap-blob#1]
I've partially renamed things from 'datatype' to 'type', but the problem is that "type" is also used for mimetype, which could cause some confusion.

But also "types" is used in RFC8620 for PushSubscriptions.

**Comment by dehart** [comment]
Personally I like `entityType` or `entityName` but as you said, `type` is used in other places therefore I think consistency is more important.

To me `data type` feels better then `type name` but both are equally intuitive.
